### PR TITLE
Fixed composer issue and  support non-default pk name

### PR DESCRIPTION
**Pull request by kim-dongit**
- Fixed composer requirements.
- Allow for non-default pk column name for user model.
- Used env variables stated in README.md (that are consistent for the sms gateways).

Minor:

- fixed reference to sms route for json data (see fb5dabd).
- some changes in README.md,
- some clean-up and cody style changes.

Please merge and release on packagist.org.

### CODE REVIEW

**Review by paschaldev — COMMENTED** [review]
Why ignoring the composer lock file?

**Comment by kim-dongit** [comment]
There is no need it in a lib (dependencies and specific versions should be resolved in the project that is using the lib).

**Comment by paschaldev** [comment]
Ok thanks. Merged

**Comment by kim-dongit** [comment]
Thank you. Could you also publish the version on packagist.org (the composer repo)?

**Comment by paschaldev** [comment]
Done. 1.0.3

**Comment by kim-dongit** [comment]
Thanks!

**Pull request merged**
